### ISSUE TITLE
Vector: Division by zero untreated

### ISSUE THREAD

**Issue by imota** [unball/simulator#1]
We do not treat vector divisions by 0. We thought of throwing an exception, but we were worried it might hide a logic error in the program. For now, we decided to leave it untreated, and if anyone asks for such a division, the program will crash.

Any thoughts on that?

**Comment by matheusportela** [comment]
Simply throw an `ZeroDivisionError` and that will also crash the program, while informing the user that dividing a vector by 0 is forbidden.

```python
if scalar == 0:
    raise ZeroDivisionError('Vector cannot be divided by 0.')
```

**Comment by vieiramanoel** [comment]
Now using numpy.array, missing tests about it, but probably already treated in this lib. Closing issue once we are not longer using our own Vector class
